# Generated by Django 2.2.5 on 2019-10-15 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=920)),
                ('gender', models.CharField(max_length=920)),
                ('email', models.EmailField(max_length=920)),
                ('contact', models.IntegerField()),
                ('company_name', models.CharField(max_length=920)),
                ('product_interested_in', models.CharField(max_length=920)),
                ('status', models.CharField(max_length=920)),
                ('date_of_entry', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'All Leads Lists',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('full_name', models.CharField(max_length=920)),
                ('role', models.CharField(max_length=920)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=920)),
                ('contact', models.IntegerField()),
                ('company_name', models.CharField(max_length=920)),
                ('status', models.CharField(max_length=920)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'All Teams Lists',
            },
        ),
    ]
