# Generated by Django 2.2.5 on 2019-10-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending Status', 'Pending Status'), ('In Process Status', 'In Process Status'), ('Approved Status', 'Approved Status'), ('Rejected Status', 'Rejected Status')], max_length=920),
        ),
    ]
