# Generated by Django 2.2.5 on 2019-10-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0002_auto_20191015_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(2, 'admin'), (1, 'super_admin'), (3, 'team')], max_length=920),
        ),
    ]
