# Generated by Django 2.2.5 on 2019-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0002_auto_20191018_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('InProcess', 'InProcess'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=920),
        ),
    ]
