# Generated by Django 2.2.5 on 2019-10-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0003_auto_20191018_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=920),
        ),
    ]
