# Generated by Django 2.2.5 on 2019-10-15 10:12

from django.db import migrations, models
import sspn_lead_manager_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0005_auto_20191015_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='sr_no',
            field=models.IntegerField(default=sspn_lead_manager_app.models.AllLeads.sr_number_genrator),
        ),
    ]
