# Generated by Django 2.2.5 on 2019-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0007_auto_20191015_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='allleads',
            name='city',
            field=models.CharField(blank=True, max_length=920),
        ),
        migrations.AddField(
            model_name='allleads',
            name='profession',
            field=models.CharField(blank=True, max_length=920),
        ),
    ]
