# Generated by Django 2.2.5 on 2019-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0008_auto_20191015_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='contact',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
