# Generated by Django 2.2.5 on 2019-10-15 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0009_auto_20191015_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='date_of_entry',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
