# Generated by Django 2.2.5 on 2019-10-15 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0010_auto_20191015_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
