# Generated by Django 2.2.5 on 2019-10-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0011_auto_20191015_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='profession',
            field=models.CharField(blank=True, choices=[('Salaried', 'Salaried'), ('Business', 'Business'), ('Self Employed', 'Self Employed'), ('Other', 'Other')], max_length=920),
        ),
    ]
