# Generated by Django 2.2.5 on 2019-10-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0012_auto_20191017_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='city',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Banglore', 'Banglore'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad'), ('Other', 'Other')], max_length=920),
        ),
    ]
