# Generated by Django 2.2.5 on 2019-10-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0013_auto_20191017_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='company_name',
            field=models.CharField(blank=True, choices=[('Tcs', 'Tcs'), ('LTI', 'LTI'), ('Accenture', 'Accenture'), ('Axis Bank', 'Axis Bank'), ('Infosys', 'Infosys'), ('Other', 'Other')], max_length=920),
        ),
    ]
