# Generated by Django 2.2.5 on 2019-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0014_auto_20191017_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='company_name',
            field=models.CharField(blank=True, max_length=920),
        ),
    ]
