# Generated by Django 2.2.5 on 2019-10-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0015_auto_20191017_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sr_no',
        ),
    ]
