# Generated by Django 2.2.5 on 2019-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspn_lead_manager_app', '0016_remove_team_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allleads',
            name='product_interested_in',
            field=models.CharField(blank=True, choices=[('MicroFinance', 'MicroFinance'), ('InstantSalary', 'InstantSalary'), ('ConsumerFinance', 'ConsumerFinance')], max_length=920),
        ),
    ]
